Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 02, 2024 - 21:57:30
Django version 4.2.16, using settings 'ofipensiones.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Error: That port is already in use.
Invalid HTTP_HOST header: '34.16.108.153:8080'. You may need to add '34.16.108.153' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.16.108.153:8080'. You may need to add '34.16.108.153' to ALLOWED_HOSTS.
Bad Request: /
[02/Dec/2024 21:58:17] "GET / HTTP/1.1" 400 63044
Invalid HTTP_HOST header: '34.16.108.153:8080'. You may need to add '34.16.108.153' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.16.108.153:8080'. You may need to add '34.16.108.153' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[02/Dec/2024 21:58:17] "GET /favicon.ico HTTP/1.1" 400 63005
